### ISSUE TITLE
Why can’t Stingle backup and sync all photos in iOS photo library?

### ISSUE THREAD

**Issue by imlibra** [stingle/stingle-photos-ios#48]
Why can’t Stingle backup and sync all photos in iOS photo library like Google Photos etc…? It can only add some of photo to app, but not backup everything.

**Comment by imlibra** [comment]
Any progress of this?

**Comment by alexamiryan** [comment]
This is the current task that we are working on right now. We will start internal testing of it in 3 days.

**Comment by imlibra** [comment]
It’s still not available to backup entire library

**Comment by alexamiryan** [comment]
Update is coming with auto import in 1 or 2 days, stay tuned
